version: 2
updates:
- package-ecosystem: nuget
  labels: [dependency]
  groups:
    microsoft:
      patterns: [Microsoft.*, System.*]
    xunit:
      patterns: [xunit.*]
  directory: /
  schedule:
    interval: monthly
  target-branch: main

- package-ecosystem: nuget
  labels: [dependency, support]
  groups:
    microsoft:
      patterns: [Microsoft.*, System.*]
    xunit:
      patterns: [xunit.*]
  directory: /
  schedule:
    interval: monthly
  target-branch: support/1.x
  ignore:
  - dependency-name: Newtonsoft.Json

- package-ecosystem: github-actions
  labels: [dependency]
  groups:
    actions:
      patterns: [actions/*]
  directory: /
  schedule:
    interval: monthly
  target-branch: main

- package-ecosystem: github-actions
  labels: [dependency, support]
  groups:
    actions:
      patterns: [actions/*]
  directory: /
  schedule:
    interval: monthly
  target-branch: support/1.x
