version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  target-branch: main

- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  target-branch: support/1.x

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  target-branch: main

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  target-branch: support/1.x
