name: docker

on:
  push:
    branches: [main, support/*]
    tags: ["*"]
  pull_request:
    branches: [main, support/*]

jobs:
  docker:
    name: build & run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: docker build
        run: docker build -t json-ld.net .
      - name: docker test
        run: docker run --rm json-ld.net dotnet test
